### ISSUE TITLE
xcode 6

### ISSUE THREAD

**Issue by kylemcdonald** [admsyn/OFPlugin#19]
https://gist.githubusercontent.com/neonichu/9487584/raw/97b371b79a2dfe6ccee524ff7aaaf9d887e0d27d/update_xcode_plugins

script linked to fixed it for me

**Comment by admsyn** [comment]
OFPlugin seems to be working through Xcode 6.3.2 ( #33 ). Going to close this but please re-open if there's some related installation issue in the future.
