### ISSUE TITLE
ofxOsc libs/oscpack/src/ip/posix files and header path missing

### ISSUE THREAD

**Issue by cerkut** [admsyn/OFPlugin#27]
When adding ofxOsc, we need to ensure that libs/oscpack/src/ip/posix is added both as a group and as a header search path. The second is handled, if (OFAddon.m) extraHeaderSearchPaths would return

return @[@"../../../addons/ofxOsc/libs/oscpack/src/\r../../../addons/ofxOsc/libs/oscpack/ip/posix/"

I am checking the first, will issue a PR if I can figure out.

**Comment by admsyn** [comment]
I think I've got this locally, just doing a bit of testing first :) 

It's looks like it's a combination of ofxOsc using "posix" as its lib folder identifier, a bad regex in OFPlugin, and ofxOsc not properly declaring its include paths.

**Comment by admsyn** [comment]
Ok, I think this is fixed. Exception being that openFrameworks/openFrameworks#3575 needs to be pulled for the include path to be added properly.

Can you give it a test when you have a moment? Feel free to re-open this if it isn't fixed. Thanks for the report by the way!

**Comment by cerkut** [comment]
Thank you, tested it (with manually editing ofxOsc/addon_config.mk) with the latest OFPlugin [[https://github.com/admsyn/OFPlugin/commit/6b8a6919528eb9d7f3a0fb3c112a5f224c56870e][6b8a691]], and it works.
