### ISSUE TITLE
readme update for installation via Alcatraz

### ISSUE THREAD

**Issue by firmread** [admsyn/OFPlugin#30]
Not really an issue but just a mild suggestion. (and btw, thanks for making + sharing this tool!)  

I've been using [Alcatraz](http://alcatraz.io) for managing Xcode Plugin for a while, and loving it so far. And just realized that I can install OFPlugin directly from it too. So I think maybe adding a gentle update to readme.md that mention simple installation choice via Alcatraz might make this a little easier for beginners.

**Comment by admsyn** [comment]
Sure thing, done :) Thanks for the suggestion!
