### ISSUE TITLE
Doesn't work on Xcode 6.3

### ISSUE THREAD

**Issue by admsyn** [admsyn/OFPlugin#31]
Error:
```
-[IDEWorkspace wrappedXcode3Project]: unrecognized selector sent to instance 0x7fb3010c9340
```
Looks like a bit of the plugin will have to be reworked not to use the Xcode3Project stuff.

[The problem section](https://github.com/admsyn/OFPlugin/blob/master/OFPlugin/OFPlugin.m#L232-L235)

**Comment by kylemcdonald** [comment]
ohhhh noooo!!!!

**Comment by armadillu** [comment]
Is this a giant architecture change? This plugin saves me tons of time!

**Comment by admsyn** [comment]
I don't think this is going to be a showstopper. What I somewhat unwittingly did in the first place was use two parallel sets of functionality when manipulating project files (PBXProject and Xcode3Project). The Xcode3Project API is much simpler, but is obviously pretty old :) They seem to have removed the Xcode3 stuff, so I just need to find out the mapping of semi-obscure PBXProject functionality to the Xcode3 stuff OFPlugin is using.

I'm at resonate right now so I'm a little busy but maybe I can bust this out between workshops :)

If anyone wants to take a stab at it, the basic workflow is to use [class-dump](http://stevenygard.com/projects/class-dump/) on the frameworks in Xcode to find the Obj-C functions that can be called. The sources of the functions I'm using is half-documented in comments in OFPlugin.m. It's pretty awkward, I wouldn't expect anyone to want to bother figuring it all out, but if anyone finds any hints it'd be most welcome!

**Comment by admsyn** [comment]
The current stumbling block is how to drill down from the NSApp to the PBXProject. [The line that's throwing the error](https://github.com/admsyn/OFPlugin/blob/master/OFPlugin/OFPlugin.m#L232) seems to be the trickiest part, without a direct counterpart in the PBXProject API. Once there's a way to get a grip on the PBXProject the rest should be simple enough to get together.

**Comment by admsyn** [comment]
Ok I think this is fixed, thanks to #32

**Comment by mrbichel** [comment]
Ah thanks! :D Have been missing this so much.

**Comment by jmarsico** [comment]
thanks for fixing!!
