### ISSUE TITLE
Xcode 6.3.2 update ~ doesn't open

### ISSUE THREAD

**Issue by dimitre** [admsyn/OFPlugin#33]
I've just updated Xcode and it seems to have stopped working.
Thanks for the great and useful plugin.

**Comment by a2hill** [comment]
I'm having the same issue. Is there a certain place in the DVTPlugInCompatibilityUUIDs section of the plist that we're supposed to put the new UUID? I've tried putting it first and last to no avail.

**Comment by admsyn** [comment]
It looks like there's some changes being introduced in 6.3.2 related to plugin loading. I did the usual UUID update, and got a "do you want to load this bundle" warning on the next Xcode load. Even after accepting it acts like the plugin didn't load (OFPlugin would generally log errors to the console if there were any).

http://stackoverflow.com/questions/30361228/why-are-my-xcode-plugins-such-as-clang-format-installed-with-alcatraz-no-longe

**Comment by deksden** [comment]
Here is same issue for CocoaPods plugin (solved): https://github.com/kattrali/cocoapods-xcode-plugin/issues/62

**Comment by admsyn** [comment]
Ah, simple fix then. Thanks @deksden :)
