### ISSUE TITLE
OF menu not visible after install

### ISSUE THREAD

**Issue by kontur** [admsyn/OFPlugin#34]
Hey,

I just installed OFPlugin for the first time (manually via opening the example in the git repo once after cloning it, but also: Alcatraz shows it as installed) and restarted XCode. The OF menu is nowhere to be found. Not in the main bar, nor in any of the other menu dropdowns (I saw there was a recent PR to move it https://github.com/admsyn/OFPlugin/pull/25).

Running XCode Version 6.3.2 (6D2105) on Mac 10.10.3 (14D136).

Did I miss something obvious or can anybody reproduce this?

**Comment by kontur** [comment]
Hm, classic 15-minutes-later: There now appears a OF menu as shown in the README screenshot. Not sure what caused it to not update after the first (and several consequent) XCode restarts, but anyway it is there now.

**Comment by admsyn** [comment]
¯\_(ツ)_/¯ this behaviour has been reported before ( #19 ) but I haven't been able to reproduce it locally. Thanks for reporting anyway!
