### ISSUE TITLE
OF plugin not working

### ISSUE THREAD

**Issue by roymacdonald** [admsyn/OFPlugin#35]
Hey Adam, 
hope you're doing well.
I had to reinstall my system and now the OF plugin doesn't work (Once you've began using it you can't go back :) .
The menu shows, it displays all the addon, I can get select the addons folder path.
But when I try to add an addon I get this (from the console):

OFPlugin problem! (please report the issue at https://github.com/admsyn/OFPlugin) : [<IDEWorkspace 0x7fe7bf8881e0> valueForUndefinedKey:]: this class is not key value coding-compliant for the key _wrappedContainer.
I'm going through the OFPlugin code to see what might be causing this. In the meanwhile if you know the fix just let me know!
All the best!
PD: Many thanks for this awesome plugin!

**Comment by tenedor** [comment]
It is similarly not working for me. I just installed OFPlugin for the first time, so I do not know if I have done something wrong, but after setting the addons path, Add addon gives me a list of my downloaded addons but clicking them has no effect. (Unlike Roy, I do not get an error log in my console.)

**Comment by roymacdonald** [comment]
Hi @tenedor the error log doesn't show up on xcode's consoles. It shows up on the system console.
So far I have no fix for it.
Best!

**Comment by admsyn** [comment]
Hey @roymacdonald, just saw this. What version of Xcode are you on? I think the _wrappedContainer call was a workaround for Xcode 6.3, so if you're using an earlier version you may want to checkout around 83be6b76e2ae22672086324fd5bb34cea51a68dd or so

**Comment by roymacdonald** [comment]
Hey @admsyn, thanks. that was it. now it works again.
:D 
I'm using xcode 6.1.1

best!

**Comment by tenedor** [comment]
Perfect, thanks @admsyn and @roymacdonald! This fixed it for me on xcode 6.2

**Comment by admsyn** [comment]
Cool, good to hear :) There is a note about this in the README btw, but re-reading it now it's not nearly clear enough. Will fix.
